version: '3.7'

services:
  app:
    container_name: myapp
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000

     

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - '8080:9090'
    
  grafana:
    image: grafana/grafana:6.5.2
    volumes:
      - grafana_data:/data
    ports:
      - '3000:3000'

volumes:
  prometheus_data:
  grafana_data: