version: '3.7'

networks:
  loki:

services:
  app:
    container_name: myapp
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./store:/my_app
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - loki

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - '9090:9090'
    
  grafana:
    image: grafana/grafana:6.5.2
    volumes:
      - grafana_data:/data
    ports:
      - '3000:3000'
    networks:
      - loki

  loki:
    image: grafana/loki:2.8.0
    volumes:
      - ./loki:/etc/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.8.0
    ports:
      - "9080:9080"
    volumes:
      - ./store/log:/var/log
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki

volumes:
  prometheus_data:
  grafana_data: