global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
      - targets: [host.docker.internal:8000]

  - job_name: monitoring_2
    metrics_path: /api/metrics
    static_configs:
      - targets: [ host.docker.internal:8000 ]