# Generated by Django 4.2.1 on 2023-06-18 10:32

from django.db import migrations, models
import django_prometheus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('car'), models.Model),
        ),
    ]
